---
- name: Install HashiCorp Vault
  include_tasks: install.yml

- name: Configure Vault UI ingress
  include_tasks: ingress.yml
  when: vault_ingress_enabled | default(false) | bool

- name: Install External Secrets Operator
  include_tasks: external-secrets.yml
